FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src/ ./src/
COPY public/ ./public
COPY next.config.ts ./
COPY tailwind.config.ts ./
COPY next-env.d.ts ./
COPY eslint.config.mjs ./
COPY postcss.config.mjs ./
COPY eslint.config.mjs ./
COPY tsconfig.json ./

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]